# Usa una imagen base de Python
FROM python:3.12.3-slim

WORKDIR /backend

COPY ./backend/requirements.txt /backend/
RUN pip install -r requirements.txt

COPY ./backend /backend

CMD ["python", "/backend/app.py"]
